version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@host.docker.internal:${MONGO_PORT}
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_ROOT_PORT: ${MONGO_PORT}
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - app-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-net:
    driver: bridge
